### ISSUE TITLE
When clicking on "Medium auswählen" language switch to English is happening

### ISSUE THREAD

**Issue by Protoss78** [Tokencube/bcms#55]
All pages are described in German language. But when I click on "Medium auswählen" on "Audio erstellen" page, the description in the popup window is suddenly English. The language should be consistent throughout the web application.
![bildschirmfoto vom 2015-01-25 02 23 04](https://cloud.githubusercontent.com/assets/4738976/5889799/1d4668a2-a439-11e4-8ce3-005ac39473be.png)

**Comment by BioPhoton** [comment]
language update do not resolfe this issue probably will fix in future
